events {}

http {

 upstream asia_cluster {

   server asia-api-1:3000;
   server asia-api-2:3000;

 }

 upstream us_cluster {

   server us-api-1:3000;
   server us-api-2:3000;

 }

 server {

   listen 80;

   location / {

     proxy_pass http://asia_cluster;

   }

 }

}